// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1j67u5aEoQuDu8ldftzq0VbzuBuKJUE4',
    appId: '1:1008921593532:web:9520d065b8fd9081fff2b9',
    messagingSenderId: '1008921593532',
    projectId: 'bundledapp',
    authDomain: 'bundledapp.firebaseapp.com',
    databaseURL: 'https://bundledapp-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bundledapp.appspot.com',
    measurementId: 'G-XZ28SXZ80S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAERUpALPSCgex1QTWIGM-lVvWJqxcmdac',
    appId: '1:1008921593532:android:3a31d57f5b59094efff2b9',
    messagingSenderId: '1008921593532',
    projectId: 'bundledapp',
    databaseURL: 'https://bundledapp-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bundledapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBD6HuRE-KWNCOOB9cDP5R5jDwiogpOwPI',
    appId: '1:1008921593532:ios:787420d35a60c34cfff2b9',
    messagingSenderId: '1008921593532',
    projectId: 'bundledapp',
    databaseURL: 'https://bundledapp-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bundledapp.appspot.com',
    iosClientId: '1008921593532-ua9iua68q76qcjmqorubeqqgufhqvfgl.apps.googleusercontent.com',
    iosBundleId: 'com.simplyshare.bundledapp',
  );
}
